//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemasTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id { get; set; }
        public string NombreCompleto { get; set; }
        public string Cedula { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Rol { get; set; }
    }
}
